[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd api && npm install && node index.js & cd ../scraper && pip install -r requirements.txt && python app.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 100

[service]
internal_port = 3000
